# environment.yml
name: soybean-alt-rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core bioinformatics tools
  - fastqc=0.12.1
  - multiqc=1.25.1
  - trimmomatic=0.39
  - hisat2=2.2.1
  - samtools=1.19.2
  - subread=2.0.6
  
  # Python environment for analysis
  - python=3.12
  - snakemake=7.32.4
  - pydeseq2=0.4.1    # Python implementation of DESeq2
  
  # Python packages for data handling and visualization
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  
  - r-base=4.3.0# environment.yml