# config/config.yml

samples:
  - Alternaria_T14_1
  - Alternaria_T14_2
  - Alternaria_T14_3
  - Control_T14_1
  - Control_T14_2
  - Control_T14_3
  - Control_T14_4

# Reference Genomes and Annotations
references:
  glygenome: "resources/genomes/Gmax_880_v6.0.fa"
  altgenome: "resources/genomes/Alternaria_alternata_gca_004154755.ASM415475v1.dna.toplevel.fa"
  glyannotation: "resources/annotations/Gmax_880_Wm82.a6.v1.gene.gff3"
  altannotation: "resources/annotations/Alternaria_alternata_gca_004154755.ASM415475v1.60.gtf"

# Parameters for key tools
params:
  trimmomatic: "ILLUMINACLIP:resources/adapters/NexteraPE-PE.fa:2:30:10:2:True LEADING:3 TRAILING:3 SLIDINGWINDOW:5:18 MINLEN:30"
  hisat2_strandedness: "RF" # For reverse-stranded libraries
  featurecounts_strandedness: "2"

# Design matrix for Differential Expression
design:
  condition: [Alternaria_T14_1, Alternaria_T14_2, Alternaria_T14_3, Control_T14_1, Control_T14_2, Control_T14_3, Control_T14_4]